language: rust
rust:
  - stable
  - beta
  - nightly
cache:
  cargo: true
  timeout: 1000
filter_secrets: false
os:
  # - linux
  #- osx
  - windows
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update && sudo apt-get install -y libasound2-dev libudev-dev libxcb-shape0-dev libxcb-xfixes0-dev; fi
  - mkdir discord
  - pushd discord
  - export DISCORD_GAME_SDK_PATH=$(pwd)
  - curl -LO https://dl-game-sdk.discordapp.net/latest/discord_game_sdk.zip
  - unzip discord_game_sdk.zip
  - popd
  - rustup component add clippy rustfmt
script:
  - cargo test
  - cargo clippy
  - cargo build --release
deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    branch: master
    rust: stable
matrix:
  allow_failures:
    - rust: beta
    - rust: nightly
