language: rust
rust:
  - stable
  - beta
cache:
  cargo: true
  timeout: 1000
filter_secrets: false
os:
  - linux
  - osx
  - windows
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update && sudo apt-get install -y libudev-dev zlib1g-dev alsa libasound2-dev; fi
  - rustup component add clippy
script:
  - cargo test --features client
  - cargo clippy --features client
  - cargo build --release --features client
deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    branch: master
    rust: stable
matrix:
  allow_failures:
    - rust: beta
