language: rust
rust:
  - stable
  - beta
cache:
  cargo: true
  timeout: 1000
filter_secrets: false
os:
  - windows
before_install:
  - rustup default $TRAVIS_RUST_VERSION-msvc
  - rustup component add clippy
  - cargo install --git https://github.com/boringcactus/wasm-pack.git --force
script:
  - cargo clippy
  - wasm-pack build --target no-modules -- --package dynamaze
deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    branch: master
    rust: stable
matrix:
  allow_failures:
    - rust: beta
