language: rust
rust: stable
cache: cargo
filter_secrets: false
os:
  - linux
  - osx
  - windows
script:
  - cargo test
  - cargo build --release
deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    branch: master
