[package]
name = "dynamaze"
version = "0.1.0"
authors = ["Melody Horn <melody@boringcactus.com>"]
edition = "2018"

[dependencies]
piston = "0.42.0"
piston2d-graphics = "0.30.0"
pistoncore-glutin_window = "0.54.0"
piston2d-opengl_graphics = "0.59.0"
rand = "0.7.0"
bincode = "1.1.2"
serde = { version = "1.0.88", features = ["derive"] }
clipboard = "0.5.0"
rodio = "0.9.0"
lazy_static = "1.2.0"
conrod_core = "0.66.0"
conrod_piston = "0.66.0"
toml = "0.5.1"
gilrs = "0.7.1"
discord_game_sdk = "0.3.1"
log = "0.4.8"
env_logger = "0.6.2"

[patch.crates-io]
bindgen = { git = "https://github.com/rust-lang/rust-bindgen", tag = "v0.50.0" }
