[package]
name = "dynamaze"
version = "0.1.0"
authors = ["Melody Horn <melody@boringcactus.com>"]
edition = "2018"

[features]
default = ['client']
client = [
    'piston',
    'piston2d-graphics',
    'pistoncore-glutin_window',
    'piston2d-opengl_graphics',
    'clipboard',
    'rodio',
    'conrod_core',
    'conrod_piston',
    'igd',
    'get_if_addrs',
    'gilrs',
]

[dependencies]
piston = { version = "0.42.0", optional = true }
piston2d-graphics = { version = "0.30.0", optional = true }
pistoncore-glutin_window = { version = "0.54.0", optional = true }
piston2d-opengl_graphics = { version = "0.59.0", optional = true }
rand = "0.7.2"
bincode = "1.2.0"
serde = { version = "1.0.103", features = ["derive"] }
clipboard = { version = "0.5.0", optional = true }
tokio = "0.1.21"
futures = "0.1.25"
bytes = "0.4.12"
rodio = { version = "0.10.0", optional = true }
lazy_static = "1.4.0"
conrod_core = { version = "0.68.0", optional = true }
conrod_piston = { version = "0.68.0", optional = true }
igd = { version = "0.9.1", optional = true }
get_if_addrs = { version = "0.5.3", optional = true }
toml = "0.5.5"
gilrs = { version = "0.7.3", optional = true }

[[bin]]
name = "dynamaze"
required-features = ["client"]
