[package]
name = "dynamaze"
version = "0.1.0"
authors = ["Melody Horn <melody@boringcactus.com>"]
edition = "2018"

[dependencies]
piston = "0.42.0"
piston2d-graphics = "0.30.0"
pistoncore-glutin_window = "0.54.0"
piston2d-opengl_graphics = "0.59.0"
rand = "0.7.2"
bincode = "1.2.0"
serde = { version = "1.0.103", features = ["derive"] }
clipboard = "0.5.0"
tokio = "0.1.21"
futures = "0.1.25"
bytes = "0.4.12"
rodio = "0.10.0"
lazy_static = "1.4.0"
conrod_core = "0.68.0"
conrod_piston = "0.68.0"
igd = "0.9.1"
get_if_addrs = "0.5.3"
toml = "0.5.5"
gilrs = "0.7.3"
