[package]
name = "dynamaze"
version = "0.1.0"
authors = ["Melody Horn <melody@boringcactus.com>"]
edition = "2018"

[features]
client = [
    'quicksilver',
    'clipboard',
    'rodio',
    'igd',
    'get_if_addrs',
    'gilrs',
]

[dependencies]
quicksilver = { version = "0.3.20", features = ["complex_shapes", "immi_ui", "fonts", "gamepads", "saving", "sounds"], default-features = false, optional = true }
rand = "0.7.2"
bincode = "1.2.0"
serde = { version = "1.0.103", features = ["derive"] }
clipboard = { version = "0.5.0", optional = true }
tokio = "0.1.21"
futures = "0.1.25"
bytes = "0.4.12"
rodio = { version = "0.10.0", optional = true }
lazy_static = "1.4.0"
igd = { version = "0.9.1", optional = true }
get_if_addrs = { version = "0.5.3", optional = true }
toml = "0.5.5"
gilrs = { version = "0.7.3", optional = true }

[[bin]]
name = "dynamaze"
required-features = ["client"]
